import { Herb, CabinetConfig, CabinetProfile } from './types';

export const DEFAULT_CABINET_CONFIG: CabinetConfig = {
  rows: 7,
  cols: 8,
};

// ─── 中草药柜 预置药材 ─────────────────────────────────────────────────────────
export const DEFAULT_HERBS: Herb[] = [
  // 第1行
  { id: 'h001', name: '黄芪', nameTraditional: '黃芪', pricePerGram: 0.08, position: { row: 0, col: 0, side: 'left' }, category: '补气' },
  { id: 'h002', name: '党参', nameTraditional: '黨參', pricePerGram: 0.12, position: { row: 0, col: 0, side: 'right' }, category: '补气' },
  { id: 'h003', name: '白术', nameTraditional: '白朮', pricePerGram: 0.06, position: { row: 0, col: 1, side: 'left' }, category: '补气' },
  { id: 'h004', name: '茯苓', nameTraditional: '茯苓', pricePerGram: 0.05, position: { row: 0, col: 1, side: 'right' }, category: '利水' },
  { id: 'h005', name: '甘草', nameTraditional: '甘草', pricePerGram: 0.04, position: { row: 0, col: 2, side: 'left' }, category: '补气' },
  { id: 'h006', name: '当归', nameTraditional: '當歸', pricePerGram: 0.10, position: { row: 0, col: 2, side: 'right' }, category: '补血' },
  { id: 'h007', name: '熟地', nameTraditional: '熟地', pricePerGram: 0.06, position: { row: 0, col: 3, side: 'left' }, category: '补血' },
  { id: 'h008', name: '白芍', nameTraditional: '白芍', pricePerGram: 0.05, position: { row: 0, col: 3, side: 'right' }, category: '补血' },
  { id: 'h009', name: '川芎', nameTraditional: '川芎', pricePerGram: 0.08, position: { row: 0, col: 4, side: 'left' }, category: '活血' },
  { id: 'h010', name: '红花', nameTraditional: '紅花', pricePerGram: 0.15, position: { row: 0, col: 4, side: 'right' }, category: '活血' },
  { id: 'h011', name: '桃仁', nameTraditional: '桃仁', pricePerGram: 0.10, position: { row: 0, col: 5, side: 'left' }, category: '活血' },
  { id: 'h012', name: '丹参', nameTraditional: '丹參', pricePerGram: 0.08, position: { row: 0, col: 5, side: 'right' }, category: '活血' },
  { id: 'h013', name: '柴胡', nameTraditional: '柴胡', pricePerGram: 0.10, position: { row: 0, col: 6, side: 'left' }, category: '解表' },
  { id: 'h014', name: '黄芩', nameTraditional: '黃芩', pricePerGram: 0.06, position: { row: 0, col: 6, side: 'right' }, category: '清热' },
  { id: 'h015', name: '连翘', nameTraditional: '連翹', pricePerGram: 0.08, position: { row: 0, col: 7, side: 'left' }, category: '清热' },
  { id: 'h016', name: '金银花', nameTraditional: '金銀花', pricePerGram: 0.12, position: { row: 0, col: 7, side: 'right' }, category: '清热' },
  // 第2行
  { id: 'h017', name: '麻黄', nameTraditional: '麻黃', pricePerGram: 0.05, position: { row: 1, col: 0, side: 'left' }, category: '解表' },
  { id: 'h018', name: '桂枝', nameTraditional: '桂枝', pricePerGram: 0.04, position: { row: 1, col: 0, side: 'right' }, category: '解表' },
  { id: 'h019', name: '防风', nameTraditional: '防風', pricePerGram: 0.08, position: { row: 1, col: 1, side: 'left' }, category: '解表' },
  { id: 'h020', name: '荆芥', nameTraditional: '荊芥', pricePerGram: 0.05, position: { row: 1, col: 1, side: 'right' }, category: '解表' },
  { id: 'h021', name: '薄荷', nameTraditional: '薄荷', pricePerGram: 0.06, position: { row: 1, col: 2, side: 'left' }, category: '解表' },
  { id: 'h022', name: '生姜', nameTraditional: '生薑', pricePerGram: 0.03, position: { row: 1, col: 2, side: 'right' }, category: '解表' },
  { id: 'h023', name: '大枣', nameTraditional: '大棗', pricePerGram: 0.04, position: { row: 1, col: 3, side: 'left' }, category: '补气' },
  { id: 'h024', name: '陈皮', nameTraditional: '陳皮', pricePerGram: 0.06, position: { row: 1, col: 3, side: 'right' }, category: '理气' },
  { id: 'h025', name: '半夏', nameTraditional: '半夏', pricePerGram: 0.08, position: { row: 1, col: 4, side: 'left' }, category: '化痰' },
  { id: 'h026', name: '枳壳', nameTraditional: '枳殼', pricePerGram: 0.05, position: { row: 1, col: 4, side: 'right' }, category: '理气' },
  { id: 'h027', name: '厚朴', nameTraditional: '厚朴', pricePerGram: 0.06, position: { row: 1, col: 5, side: 'left' }, category: '理气' },
  { id: 'h028', name: '木香', nameTraditional: '木香', pricePerGram: 0.08, position: { row: 1, col: 5, side: 'right' }, category: '理气' },
  { id: 'h029', name: '砂仁', nameTraditional: '砂仁', pricePerGram: 0.20, position: { row: 1, col: 6, side: 'left' }, category: '理气' },
  { id: 'h030', name: '香附', nameTraditional: '香附', pricePerGram: 0.05, position: { row: 1, col: 6, side: 'right' }, category: '理气' },
  { id: 'h031', name: '苍术', nameTraditional: '蒼朮', pricePerGram: 0.06, position: { row: 1, col: 7, side: 'left' }, category: '化湿' },
  { id: 'h032', name: '藿香', nameTraditional: '藿香', pricePerGram: 0.06, position: { row: 1, col: 7, side: 'right' }, category: '化湿' },
  // 第3行
  { id: 'h033', name: '黄连', nameTraditional: '黃連', pricePerGram: 0.15, position: { row: 2, col: 0, side: 'left' }, category: '清热' },
  { id: 'h034', name: '黄柏', nameTraditional: '黃柏', pricePerGram: 0.06, position: { row: 2, col: 0, side: 'right' }, category: '清热' },
  { id: 'h035', name: '栀子', nameTraditional: '梔子', pricePerGram: 0.05, position: { row: 2, col: 1, side: 'left' }, category: '清热' },
  { id: 'h036', name: '石膏', nameTraditional: '石膏', pricePerGram: 0.02, position: { row: 2, col: 1, side: 'right' }, category: '清热' },
  { id: 'h037', name: '知母', nameTraditional: '知母', pricePerGram: 0.06, position: { row: 2, col: 2, side: 'left' }, category: '清热' },
  { id: 'h038', name: '龙胆草', nameTraditional: '龍膽草', pricePerGram: 0.10, position: { row: 2, col: 2, side: 'right' }, category: '清热' },
  { id: 'h039', name: '大黄', nameTraditional: '大黃', pricePerGram: 0.05, position: { row: 2, col: 3, side: 'left' }, category: '泻下' },
  { id: 'h040', name: '芒硝', nameTraditional: '芒硝', pricePerGram: 0.03, position: { row: 2, col: 3, side: 'right' }, category: '泻下' },
  { id: 'h041', name: '附子', nameTraditional: '附子', pricePerGram: 0.10, position: { row: 2, col: 4, side: 'left' }, category: '温里' },
  { id: 'h042', name: '干姜', nameTraditional: '乾薑', pricePerGram: 0.04, position: { row: 2, col: 4, side: 'right' }, category: '温里' },
  { id: 'h043', name: '肉桂', nameTraditional: '肉桂', pricePerGram: 0.08, position: { row: 2, col: 5, side: 'left' }, category: '温里' },
  { id: 'h044', name: '吴茱萸', nameTraditional: '吳茱萸', pricePerGram: 0.08, position: { row: 2, col: 5, side: 'right' }, category: '温里' },
  { id: 'h045', name: '泽泻', nameTraditional: '澤瀉', pricePerGram: 0.05, position: { row: 2, col: 6, side: 'left' }, category: '利水' },
  { id: 'h046', name: '猪苓', nameTraditional: '豬苓', pricePerGram: 0.10, position: { row: 2, col: 6, side: 'right' }, category: '利水' },
  { id: 'h047', name: '车前子', nameTraditional: '車前子', pricePerGram: 0.05, position: { row: 2, col: 7, side: 'left' }, category: '利水' },
  { id: 'h048', name: '薏苡仁', nameTraditional: '薏苡仁', pricePerGram: 0.04, position: { row: 2, col: 7, side: 'right' }, category: '利水' },
  // 第4行
  { id: 'h049', name: '山药', nameTraditional: '山藥', pricePerGram: 0.05, position: { row: 3, col: 0, side: 'left' }, category: '补气' },
  { id: 'h050', name: '枸杞', nameTraditional: '枸杞', pricePerGram: 0.08, position: { row: 3, col: 0, side: 'right' }, category: '补阴' },
  { id: 'h051', name: '麦冬', nameTraditional: '麥冬', pricePerGram: 0.10, position: { row: 3, col: 1, side: 'left' }, category: '补阴' },
  { id: 'h052', name: '天冬', nameTraditional: '天冬', pricePerGram: 0.10, position: { row: 3, col: 1, side: 'right' }, category: '补阴' },
  { id: 'h053', name: '玄参', nameTraditional: '玄參', pricePerGram: 0.06, position: { row: 3, col: 2, side: 'left' }, category: '清热' },
  { id: 'h054', name: '生地', nameTraditional: '生地', pricePerGram: 0.05, position: { row: 3, col: 2, side: 'right' }, category: '清热' },
  { id: 'h055', name: '牡丹皮', nameTraditional: '牡丹皮', pricePerGram: 0.08, position: { row: 3, col: 3, side: 'left' }, category: '清热' },
  { id: 'h056', name: '赤芍', nameTraditional: '赤芍', pricePerGram: 0.06, position: { row: 3, col: 3, side: 'right' }, category: '清热' },
  { id: 'h057', name: '三七', nameTraditional: '三七', pricePerGram: 0.30, position: { row: 3, col: 4, side: 'left' }, category: '活血' },
  { id: 'h058', name: '延胡索', nameTraditional: '延胡索', pricePerGram: 0.10, position: { row: 3, col: 4, side: 'right' }, category: '活血' },
  { id: 'h059', name: '乳香', nameTraditional: '乳香', pricePerGram: 0.12, position: { row: 3, col: 5, side: 'left' }, category: '活血' },
  { id: 'h060', name: '没药', nameTraditional: '沒藥', pricePerGram: 0.12, position: { row: 3, col: 5, side: 'right' }, category: '活血' },
  { id: 'h061', name: '天麻', nameTraditional: '天麻', pricePerGram: 0.25, position: { row: 3, col: 6, side: 'left' }, category: '平肝' },
  { id: 'h062', name: '钩藤', nameTraditional: '鉤藤', pricePerGram: 0.08, position: { row: 3, col: 6, side: 'right' }, category: '平肝' },
  { id: 'h063', name: '菊花', nameTraditional: '菊花', pricePerGram: 0.08, position: { row: 3, col: 7, side: 'left' }, category: '清热' },
  { id: 'h064', name: '桑叶', nameTraditional: '桑葉', pricePerGram: 0.04, position: { row: 3, col: 7, side: 'right' }, category: '解表' },
  // 第5行
  { id: 'h065', name: '杏仁', nameTraditional: '杏仁', pricePerGram: 0.06, position: { row: 4, col: 0, side: 'left' }, category: '止咳' },
  { id: 'h066', name: '桔梗', nameTraditional: '桔梗', pricePerGram: 0.06, position: { row: 4, col: 0, side: 'right' }, category: '止咳' },
  { id: 'h067', name: '前胡', nameTraditional: '前胡', pricePerGram: 0.08, position: { row: 4, col: 1, side: 'left' }, category: '化痰' },
  { id: 'h068', name: '浙贝母', nameTraditional: '浙貝母', pricePerGram: 0.15, position: { row: 4, col: 1, side: 'right' }, category: '化痰' },
  { id: 'h069', name: '百部', nameTraditional: '百部', pricePerGram: 0.06, position: { row: 4, col: 2, side: 'left' }, category: '止咳' },
  { id: 'h070', name: '紫菀', nameTraditional: '紫菀', pricePerGram: 0.06, position: { row: 4, col: 2, side: 'right' }, category: '止咳' },
  { id: 'h071', name: '款冬花', nameTraditional: '款冬花', pricePerGram: 0.10, position: { row: 4, col: 3, side: 'left' }, category: '止咳' },
  { id: 'h072', name: '白前', nameTraditional: '白前', pricePerGram: 0.06, position: { row: 4, col: 3, side: 'right' }, category: '化痰' },
  { id: 'h073', name: '龙骨', nameTraditional: '龍骨', pricePerGram: 0.08, position: { row: 4, col: 4, side: 'left' }, category: '安神' },
  { id: 'h074', name: '牡蛎', nameTraditional: '牡蠣', pricePerGram: 0.04, position: { row: 4, col: 4, side: 'right' }, category: '安神' },
  { id: 'h075', name: '酸枣仁', nameTraditional: '酸棗仁', pricePerGram: 0.20, position: { row: 4, col: 5, side: 'left' }, category: '安神' },
  { id: 'h076', name: '远志', nameTraditional: '遠志', pricePerGram: 0.10, position: { row: 4, col: 5, side: 'right' }, category: '安神' },
  { id: 'h077', name: '山楂', nameTraditional: '山楂', pricePerGram: 0.04, position: { row: 4, col: 6, side: 'left' }, category: '消食' },
  { id: 'h078', name: '神曲', nameTraditional: '神麯', pricePerGram: 0.04, position: { row: 4, col: 6, side: 'right' }, category: '消食' },
  { id: 'h079', name: '麦芽', nameTraditional: '麥芽', pricePerGram: 0.03, position: { row: 4, col: 7, side: 'left' }, category: '消食' },
  { id: 'h080', name: '鸡内金', nameTraditional: '雞內金', pricePerGram: 0.10, position: { row: 4, col: 7, side: 'right' }, category: '消食' },
  // 第6行
  { id: 'h081', name: '独活', nameTraditional: '獨活', pricePerGram: 0.06, position: { row: 5, col: 0, side: 'left' }, category: '祛风湿' },
  { id: 'h082', name: '羌活', nameTraditional: '羌活', pricePerGram: 0.10, position: { row: 5, col: 0, side: 'right' }, category: '祛风湿' },
  { id: 'h083', name: '秦艽', nameTraditional: '秦艽', pricePerGram: 0.08, position: { row: 5, col: 1, side: 'left' }, category: '祛风湿' },
  { id: 'h084', name: '威灵仙', nameTraditional: '威靈仙', pricePerGram: 0.06, position: { row: 5, col: 1, side: 'right' }, category: '祛风湿' },
  { id: 'h085', name: '桑寄生', nameTraditional: '桑寄生', pricePerGram: 0.05, position: { row: 5, col: 2, side: 'left' }, category: '祛风湿' },
  { id: 'h086', name: '杜仲', nameTraditional: '杜仲', pricePerGram: 0.08, position: { row: 5, col: 2, side: 'right' }, category: '补阳' },
  { id: 'h087', name: '续断', nameTraditional: '續斷', pricePerGram: 0.06, position: { row: 5, col: 3, side: 'left' }, category: '补阳' },
  { id: 'h088', name: '牛膝', nameTraditional: '牛膝', pricePerGram: 0.06, position: { row: 5, col: 3, side: 'right' }, category: '活血' },
  { id: 'h089', name: '补骨脂', nameTraditional: '補骨脂', pricePerGram: 0.06, position: { row: 5, col: 4, side: 'left' }, category: '补阳' },
  { id: 'h090', name: '淫羊藿', nameTraditional: '淫羊藿', pricePerGram: 0.08, position: { row: 5, col: 4, side: 'right' }, category: '补阳' },
  { id: 'h091', name: '肉苁蓉', nameTraditional: '肉蓯蓉', pricePerGram: 0.15, position: { row: 5, col: 5, side: 'left' }, category: '补阳' },
  { id: 'h092', name: '巴戟天', nameTraditional: '巴戟天', pricePerGram: 0.12, position: { row: 5, col: 5, side: 'right' }, category: '补阳' },
  { id: 'h093', name: '五味子', nameTraditional: '五味子', pricePerGram: 0.10, position: { row: 5, col: 6, side: 'left' }, category: '收涩' },
  { id: 'h094', name: '山茱萸', nameTraditional: '山茱萸', pricePerGram: 0.10, position: { row: 5, col: 6, side: 'right' }, category: '收涩' },
  { id: 'h095', name: '芡实', nameTraditional: '芡實', pricePerGram: 0.06, position: { row: 5, col: 7, side: 'left' }, category: '收涩' },
  { id: 'h096', name: '莲子', nameTraditional: '蓮子', pricePerGram: 0.06, position: { row: 5, col: 7, side: 'right' }, category: '补气' },
  // 第7行
  { id: 'h097', name: '蒲公英', nameTraditional: '蒲公英', pricePerGram: 0.04, position: { row: 6, col: 0, side: 'left' }, category: '清热' },
  { id: 'h098', name: '板蓝根', nameTraditional: '板藍根', pricePerGram: 0.04, position: { row: 6, col: 0, side: 'right' }, category: '清热' },
  { id: 'h099', name: '白花蛇舌草', nameTraditional: '白花蛇舌草', pricePerGram: 0.04, position: { row: 6, col: 1, side: 'left' }, category: '清热' },
  { id: 'h100', name: '鱼腥草', nameTraditional: '魚腥草', pricePerGram: 0.04, position: { row: 6, col: 1, side: 'right' }, category: '清热' },
  { id: 'h101', name: '白芷', nameTraditional: '白芷', pricePerGram: 0.05, position: { row: 6, col: 2, side: 'left' }, category: '解表' },
  { id: 'h102', name: '细辛', nameTraditional: '細辛', pricePerGram: 0.10, position: { row: 6, col: 2, side: 'right' }, category: '解表' },
  { id: 'h103', name: '葛根', nameTraditional: '葛根', pricePerGram: 0.05, position: { row: 6, col: 3, side: 'left' }, category: '解表' },
  { id: 'h104', name: '升麻', nameTraditional: '升麻', pricePerGram: 0.06, position: { row: 6, col: 3, side: 'right' }, category: '解表' },
  { id: 'h105', name: '地龙', nameTraditional: '地龍', pricePerGram: 0.12, position: { row: 6, col: 4, side: 'left' }, category: '平肝' },
  { id: 'h106', name: '僵蚕', nameTraditional: '僵蠶', pricePerGram: 0.12, position: { row: 6, col: 4, side: 'right' }, category: '平肝' },
  { id: 'h107', name: '太子参', nameTraditional: '太子參', pricePerGram: 0.15, position: { row: 6, col: 5, side: 'left' }, category: '补气' },
  { id: 'h108', name: '西洋参', nameTraditional: '西洋參', pricePerGram: 0.50, position: { row: 6, col: 5, side: 'right' }, category: '补气' },
  { id: 'h109', name: '沉香', nameTraditional: '沉香', pricePerGram: 0.30, position: { row: 6, col: 6, side: 'left' }, category: '理气' },
  { id: 'h110', name: '檀香', nameTraditional: '檀香', pricePerGram: 0.20, position: { row: 6, col: 6, side: 'right' }, category: '理气' },
  { id: 'h111', name: '琥珀', nameTraditional: '琥珀', pricePerGram: 0.25, position: { row: 6, col: 7, side: 'left' }, category: '安神' },
  { id: 'h112', name: '朱砂', nameTraditional: '朱砂', pricePerGram: 0.15, position: { row: 6, col: 7, side: 'right' }, category: '安神' },
];

// ─── 饮片柜 预置药材 ─────────────────────────────────────────────────────────
// 饮片是中药材经过炮制加工后的成品，售价通常比生药高
export const DEFAULT_PIAN_HERBS: Herb[] = [
  // 第1行 — 根茎类饮片
  { id: 'p001', name: '炙黄芪', nameTraditional: '炙黃芪', pricePerGram: 0.12, position: { row: 0, col: 0, side: 'left' }, category: '补气饮片' },
  { id: 'p002', name: '炒白术', nameTraditional: '炒白朮', pricePerGram: 0.10, position: { row: 0, col: 0, side: 'right' }, category: '补气饮片' },
  { id: 'p003', name: '制半夏', nameTraditional: '製半夏', pricePerGram: 0.15, position: { row: 0, col: 1, side: 'left' }, category: '化痰饮片' },
  { id: 'p004', name: '姜半夏', nameTraditional: '薑半夏', pricePerGram: 0.15, position: { row: 0, col: 1, side: 'right' }, category: '化痰饮片' },
  { id: 'p005', name: '酒当归', nameTraditional: '酒當歸', pricePerGram: 0.14, position: { row: 0, col: 2, side: 'left' }, category: '补血饮片' },
  { id: 'p006', name: '酒白芍', nameTraditional: '酒白芍', pricePerGram: 0.09, position: { row: 0, col: 2, side: 'right' }, category: '补血饮片' },
  { id: 'p007', name: '酒熟地', nameTraditional: '酒熟地', pricePerGram: 0.10, position: { row: 0, col: 3, side: 'left' }, category: '补血饮片' },
  { id: 'p008', name: '炒川芎', nameTraditional: '炒川芎', pricePerGram: 0.12, position: { row: 0, col: 3, side: 'right' }, category: '活血饮片' },
  { id: 'p009', name: '醋柴胡', nameTraditional: '醋柴胡', pricePerGram: 0.15, position: { row: 0, col: 4, side: 'left' }, category: '解表饮片' },
  { id: 'p010', name: '炒黄芩', nameTraditional: '炒黃芩', pricePerGram: 0.10, position: { row: 0, col: 4, side: 'right' }, category: '清热饮片' },
  { id: 'p011', name: '酒黄连', nameTraditional: '酒黃連', pricePerGram: 0.20, position: { row: 0, col: 5, side: 'left' }, category: '清热饮片' },
  { id: 'p012', name: '盐黄柏', nameTraditional: '鹽黃柏', pricePerGram: 0.10, position: { row: 0, col: 5, side: 'right' }, category: '清热饮片' },
  { id: 'p013', name: '炒栀子', nameTraditional: '炒梔子', pricePerGram: 0.08, position: { row: 0, col: 6, side: 'left' }, category: '清热饮片' },
  { id: 'p014', name: '酒大黄', nameTraditional: '酒大黃', pricePerGram: 0.08, position: { row: 0, col: 6, side: 'right' }, category: '泻下饮片' },
  { id: 'p015', name: '熟大黄', nameTraditional: '熟大黃', pricePerGram: 0.08, position: { row: 0, col: 7, side: 'left' }, category: '泻下饮片' },
  { id: 'p016', name: '炮附子', nameTraditional: '炮附子', pricePerGram: 0.15, position: { row: 0, col: 7, side: 'right' }, category: '温里饮片' },
  // 第2行 — 温里/理气饮片
  { id: 'p017', name: '炮姜', nameTraditional: '炮薑', pricePerGram: 0.08, position: { row: 1, col: 0, side: 'left' }, category: '温里饮片' },
  { id: 'p018', name: '盐杜仲', nameTraditional: '鹽杜仲', pricePerGram: 0.12, position: { row: 1, col: 0, side: 'right' }, category: '补阳饮片' },
  { id: 'p019', name: '盐补骨脂', nameTraditional: '鹽補骨脂', pricePerGram: 0.10, position: { row: 1, col: 1, side: 'left' }, category: '补阳饮片' },
  { id: 'p020', name: '制淫羊藿', nameTraditional: '製淫羊藿', pricePerGram: 0.12, position: { row: 1, col: 1, side: 'right' }, category: '补阳饮片' },
  { id: 'p021', name: '酒肉苁蓉', nameTraditional: '酒肉蓯蓉', pricePerGram: 0.20, position: { row: 1, col: 2, side: 'left' }, category: '补阳饮片' },
  { id: 'p022', name: '炒续断', nameTraditional: '炒續斷', pricePerGram: 0.10, position: { row: 1, col: 2, side: 'right' }, category: '补阳饮片' },
  { id: 'p023', name: '盐牛膝', nameTraditional: '鹽牛膝', pricePerGram: 0.10, position: { row: 1, col: 3, side: 'left' }, category: '活血饮片' },
  { id: 'p024', name: '醋延胡索', nameTraditional: '醋延胡索', pricePerGram: 0.15, position: { row: 1, col: 3, side: 'right' }, category: '活血饮片' },
  { id: 'p025', name: '醋香附', nameTraditional: '醋香附', pricePerGram: 0.08, position: { row: 1, col: 4, side: 'left' }, category: '理气饮片' },
  { id: 'p026', name: '麸炒枳壳', nameTraditional: '麩炒枳殼', pricePerGram: 0.08, position: { row: 1, col: 4, side: 'right' }, category: '理气饮片' },
  { id: 'p027', name: '姜厚朴', nameTraditional: '薑厚朴', pricePerGram: 0.10, position: { row: 1, col: 5, side: 'left' }, category: '理气饮片' },
  { id: 'p028', name: '炒陈皮', nameTraditional: '炒陳皮', pricePerGram: 0.09, position: { row: 1, col: 5, side: 'right' }, category: '理气饮片' },
  { id: 'p029', name: '蜜百部', nameTraditional: '蜜百部', pricePerGram: 0.10, position: { row: 1, col: 6, side: 'left' }, category: '止咳饮片' },
  { id: 'p030', name: '蜜紫菀', nameTraditional: '蜜紫菀', pricePerGram: 0.10, position: { row: 1, col: 6, side: 'right' }, category: '止咳饮片' },
  { id: 'p031', name: '蜜款冬花', nameTraditional: '蜜款冬花', pricePerGram: 0.15, position: { row: 1, col: 7, side: 'left' }, category: '止咳饮片' },
  { id: 'p032', name: '蜜麻黄', nameTraditional: '蜜麻黃', pricePerGram: 0.10, position: { row: 1, col: 7, side: 'right' }, category: '解表饮片' },
  // 第3行 — 补益类饮片
  { id: 'p033', name: '盐知母', nameTraditional: '鹽知母', pricePerGram: 0.10, position: { row: 2, col: 0, side: 'left' }, category: '清热饮片' },
  { id: 'p034', name: '炒山药', nameTraditional: '炒山藥', pricePerGram: 0.08, position: { row: 2, col: 0, side: 'right' }, category: '补气饮片' },
  { id: 'p035', name: '麸炒薏苡仁', nameTraditional: '麩炒薏苡仁', pricePerGram: 0.06, position: { row: 2, col: 1, side: 'left' }, category: '利水饮片' },
  { id: 'p036', name: '炒车前子', nameTraditional: '炒車前子', pricePerGram: 0.08, position: { row: 2, col: 1, side: 'right' }, category: '利水饮片' },
  { id: 'p037', name: '盐泽泻', nameTraditional: '鹽澤瀉', pricePerGram: 0.08, position: { row: 2, col: 2, side: 'left' }, category: '利水饮片' },
  { id: 'p038', name: '炒苍术', nameTraditional: '炒蒼朮', pricePerGram: 0.10, position: { row: 2, col: 2, side: 'right' }, category: '化湿饮片' },
  { id: 'p039', name: '醋三七', nameTraditional: '醋三七', pricePerGram: 0.40, position: { row: 2, col: 3, side: 'left' }, category: '活血饮片' },
  { id: 'p040', name: '炒丹参', nameTraditional: '炒丹參', pricePerGram: 0.12, position: { row: 2, col: 3, side: 'right' }, category: '活血饮片' },
  { id: 'p041', name: '炒山楂', nameTraditional: '炒山楂', pricePerGram: 0.06, position: { row: 2, col: 4, side: 'left' }, category: '消食饮片' },
  { id: 'p042', name: '炒麦芽', nameTraditional: '炒麥芽', pricePerGram: 0.05, position: { row: 2, col: 4, side: 'right' }, category: '消食饮片' },
  { id: 'p043', name: '炒神曲', nameTraditional: '炒神麯', pricePerGram: 0.06, position: { row: 2, col: 5, side: 'left' }, category: '消食饮片' },
  { id: 'p044', name: '炒鸡内金', nameTraditional: '炒雞內金', pricePerGram: 0.15, position: { row: 2, col: 5, side: 'right' }, category: '消食饮片' },
  { id: 'p045', name: '炒酸枣仁', nameTraditional: '炒酸棗仁', pricePerGram: 0.28, position: { row: 2, col: 6, side: 'left' }, category: '安神饮片' },
  { id: 'p046', name: '朱远志', nameTraditional: '朱遠志', pricePerGram: 0.15, position: { row: 2, col: 6, side: 'right' }, category: '安神饮片' },
  { id: 'p047', name: '煅龙骨', nameTraditional: '煅龍骨', pricePerGram: 0.10, position: { row: 2, col: 7, side: 'left' }, category: '安神饮片' },
  { id: 'p048', name: '煅牡蛎', nameTraditional: '煅牡蠣', pricePerGram: 0.06, position: { row: 2, col: 7, side: 'right' }, category: '安神饮片' },
  // 第4行 — 特殊炮制
  { id: 'p049', name: '制天麻', nameTraditional: '製天麻', pricePerGram: 0.35, position: { row: 3, col: 0, side: 'left' }, category: '平肝饮片' },
  { id: 'p050', name: '炒白芥子', nameTraditional: '炒白芥子', pricePerGram: 0.08, position: { row: 3, col: 0, side: 'right' }, category: '化痰饮片' },
  { id: 'p051', name: '蜜桔梗', nameTraditional: '蜜桔梗', pricePerGram: 0.10, position: { row: 3, col: 1, side: 'left' }, category: '止咳饮片' },
  { id: 'p052', name: '炒杏仁', nameTraditional: '炒杏仁', pricePerGram: 0.10, position: { row: 3, col: 1, side: 'right' }, category: '止咳饮片' },
  { id: 'p053', name: '盐菟丝子', nameTraditional: '鹽菟絲子', pricePerGram: 0.10, position: { row: 3, col: 2, side: 'left' }, category: '补阳饮片' },
  { id: 'p054', name: '酒女贞子', nameTraditional: '酒女貞子', pricePerGram: 0.10, position: { row: 3, col: 2, side: 'right' }, category: '补阴饮片' },
  { id: 'p055', name: '制玉竹', nameTraditional: '製玉竹', pricePerGram: 0.10, position: { row: 3, col: 3, side: 'left' }, category: '补阴饮片' },
  { id: 'p056', name: '制黄精', nameTraditional: '製黃精', pricePerGram: 0.12, position: { row: 3, col: 3, side: 'right' }, category: '补阴饮片' },
  { id: 'p057', name: '炙甘草', nameTraditional: '炙甘草', pricePerGram: 0.06, position: { row: 3, col: 4, side: 'left' }, category: '补气饮片' },
  { id: 'p058', name: '蜜黄芪', nameTraditional: '蜜黃芪', pricePerGram: 0.14, position: { row: 3, col: 4, side: 'right' }, category: '补气饮片' },
  { id: 'p059', name: '酒五味子', nameTraditional: '酒五味子', pricePerGram: 0.15, position: { row: 3, col: 5, side: 'left' }, category: '收涩饮片' },
  { id: 'p060', name: '炒山茱萸', nameTraditional: '炒山茱萸', pricePerGram: 0.15, position: { row: 3, col: 5, side: 'right' }, category: '收涩饮片' },
  { id: 'p061', name: '炒芡实', nameTraditional: '炒芡實', pricePerGram: 0.09, position: { row: 3, col: 6, side: 'left' }, category: '收涩饮片' },
  { id: 'p062', name: '麸炒莲子', nameTraditional: '麩炒蓮子', pricePerGram: 0.09, position: { row: 3, col: 6, side: 'right' }, category: '补气饮片' },
  { id: 'p063', name: '制乌头', nameTraditional: '製烏頭', pricePerGram: 0.18, position: { row: 3, col: 7, side: 'left' }, category: '温里饮片' },
  { id: 'p064', name: '煅磁石', nameTraditional: '煅磁石', pricePerGram: 0.05, position: { row: 3, col: 7, side: 'right' }, category: '安神饮片' },
];

// ─── 默认两个药柜档案 ─────────────────────────────────────────────────────────
export const DEFAULT_PROFILES: CabinetProfile[] = [
  {
    id: 'cabinet-herb',
    name: '中草藥櫃',
    description: '常用中草藥，生品為主',
    config: { rows: 7, cols: 8 },
    herbs: DEFAULT_HERBS,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cabinet-pian',
    name: '飲片櫃',
    description: '炮製加工後的飲片',
    config: { rows: 4, cols: 8 },
    herbs: DEFAULT_PIAN_HERBS,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
];
